/**
 * ICampaignManagementService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.microsoft.bingads.v9.campaignmanagement;

public interface ICampaignManagementService extends java.rmi.Remote {
    public com.microsoft.bingads.v9.campaignmanagement.AddCampaignsResponse addCampaigns(com.microsoft.bingads.v9.campaignmanagement.AddCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetCampaignsByAccountIdResponse getCampaignsByAccountId(com.microsoft.bingads.v9.campaignmanagement.GetCampaignsByAccountIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetCampaignsByIdsResponse getCampaignsByIds(com.microsoft.bingads.v9.campaignmanagement.GetCampaignsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.DeleteCampaignsResponse deleteCampaigns(com.microsoft.bingads.v9.campaignmanagement.DeleteCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.UpdateCampaignsResponse updateCampaigns(com.microsoft.bingads.v9.campaignmanagement.UpdateCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetNegativeKeywordsByCampaignIdsResponse getNegativeKeywordsByCampaignIds(com.microsoft.bingads.v9.campaignmanagement.GetNegativeKeywordsByCampaignIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.SetNegativeKeywordsToCampaignsResponse setNegativeKeywordsToCampaigns(com.microsoft.bingads.v9.campaignmanagement.SetNegativeKeywordsToCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetNegativeSitesByCampaignIdsResponse getNegativeSitesByCampaignIds(com.microsoft.bingads.v9.campaignmanagement.GetNegativeSitesByCampaignIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.SetNegativeSitesToCampaignsResponse setNegativeSitesToCampaigns(com.microsoft.bingads.v9.campaignmanagement.SetNegativeSitesToCampaignsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.AddAdGroupsResponse addAdGroups(com.microsoft.bingads.v9.campaignmanagement.AddAdGroupsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.DeleteAdGroupsResponse deleteAdGroups(com.microsoft.bingads.v9.campaignmanagement.DeleteAdGroupsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetAdGroupsByIdsResponse getAdGroupsByIds(com.microsoft.bingads.v9.campaignmanagement.GetAdGroupsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetAdGroupsByCampaignIdResponse getAdGroupsByCampaignId(com.microsoft.bingads.v9.campaignmanagement.GetAdGroupsByCampaignIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.SubmitAdGroupForApprovalResponse submitAdGroupForApproval(com.microsoft.bingads.v9.campaignmanagement.SubmitAdGroupForApprovalRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.UpdateAdGroupsResponse updateAdGroups(com.microsoft.bingads.v9.campaignmanagement.UpdateAdGroupsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetNegativeKeywordsByAdGroupIdsResponse getNegativeKeywordsByAdGroupIds(com.microsoft.bingads.v9.campaignmanagement.GetNegativeKeywordsByAdGroupIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.SetNegativeKeywordsToAdGroupsResponse setNegativeKeywordsToAdGroups(com.microsoft.bingads.v9.campaignmanagement.SetNegativeKeywordsToAdGroupsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetNegativeSitesByAdGroupIdsResponse getNegativeSitesByAdGroupIds(com.microsoft.bingads.v9.campaignmanagement.GetNegativeSitesByAdGroupIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.SetNegativeSitesToAdGroupsResponse setNegativeSitesToAdGroups(com.microsoft.bingads.v9.campaignmanagement.SetNegativeSitesToAdGroupsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.AddTargetsToLibraryResponse addTargetsToLibrary(com.microsoft.bingads.v9.campaignmanagement.AddTargetsToLibraryRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.UpdateTargetsInLibraryResponse updateTargetsInLibrary(com.microsoft.bingads.v9.campaignmanagement.UpdateTargetsInLibraryRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.DeleteTargetsFromLibraryResponse deleteTargetsFromLibrary(com.microsoft.bingads.v9.campaignmanagement.DeleteTargetsFromLibraryRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetTargetsInfoFromLibraryResponse getTargetsInfoFromLibrary(com.microsoft.bingads.v9.campaignmanagement.GetTargetsInfoFromLibraryRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetTargetsByIdsResponse getTargetsByIds(com.microsoft.bingads.v9.campaignmanagement.GetTargetsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.SetTargetToAdGroupResponse setTargetToAdGroup(com.microsoft.bingads.v9.campaignmanagement.SetTargetToAdGroupRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.DeleteTargetFromAdGroupResponse deleteTargetFromAdGroup(com.microsoft.bingads.v9.campaignmanagement.DeleteTargetFromAdGroupRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetTargetsByAdGroupIdsResponse getTargetsByAdGroupIds(com.microsoft.bingads.v9.campaignmanagement.GetTargetsByAdGroupIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.SetTargetToCampaignResponse setTargetToCampaign(com.microsoft.bingads.v9.campaignmanagement.SetTargetToCampaignRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.DeleteTargetFromCampaignResponse deleteTargetFromCampaign(com.microsoft.bingads.v9.campaignmanagement.DeleteTargetFromCampaignRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetTargetsByCampaignIdsResponse getTargetsByCampaignIds(com.microsoft.bingads.v9.campaignmanagement.GetTargetsByCampaignIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.AddAdsResponse addAds(com.microsoft.bingads.v9.campaignmanagement.AddAdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.EditorialApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.DeleteAdsResponse deleteAds(com.microsoft.bingads.v9.campaignmanagement.DeleteAdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetAdsByEditorialStatusResponse getAdsByEditorialStatus(com.microsoft.bingads.v9.campaignmanagement.GetAdsByEditorialStatusRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetAdsByIdsResponse getAdsByIds(com.microsoft.bingads.v9.campaignmanagement.GetAdsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetAdsByAdGroupIdResponse getAdsByAdGroupId(com.microsoft.bingads.v9.campaignmanagement.GetAdsByAdGroupIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.UpdateAdsResponse updateAds(com.microsoft.bingads.v9.campaignmanagement.UpdateAdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.EditorialApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.AddKeywordsResponse addKeywords(com.microsoft.bingads.v9.campaignmanagement.AddKeywordsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.EditorialApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.DeleteKeywordsResponse deleteKeywords(com.microsoft.bingads.v9.campaignmanagement.DeleteKeywordsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetKeywordsByEditorialStatusResponse getKeywordsByEditorialStatus(com.microsoft.bingads.v9.campaignmanagement.GetKeywordsByEditorialStatusRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetKeywordsByIdsResponse getKeywordsByIds(com.microsoft.bingads.v9.campaignmanagement.GetKeywordsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetKeywordsByAdGroupIdResponse getKeywordsByAdGroupId(com.microsoft.bingads.v9.campaignmanagement.GetKeywordsByAdGroupIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.UpdateKeywordsResponse updateKeywords(com.microsoft.bingads.v9.campaignmanagement.UpdateKeywordsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.EditorialApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.AppealEditorialRejectionsResponse appealEditorialRejections(com.microsoft.bingads.v9.campaignmanagement.AppealEditorialRejectionsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.AddSitePlacementsResponse addSitePlacements(com.microsoft.bingads.v9.campaignmanagement.AddSitePlacementsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.DeleteSitePlacementsResponse deleteSitePlacements(com.microsoft.bingads.v9.campaignmanagement.DeleteSitePlacementsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetSitePlacementsByIdsResponse getSitePlacementsByIds(com.microsoft.bingads.v9.campaignmanagement.GetSitePlacementsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetSitePlacementsByAdGroupIdResponse getSitePlacementsByAdGroupId(com.microsoft.bingads.v9.campaignmanagement.GetSitePlacementsByAdGroupIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.UpdateSitePlacementsResponse updateSitePlacements(com.microsoft.bingads.v9.campaignmanagement.UpdateSitePlacementsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetPlacementDetailsForUrlsResponse getPlacementDetailsForUrls(com.microsoft.bingads.v9.campaignmanagement.GetPlacementDetailsForUrlsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetEditorialReasonsByIdsResponse getEditorialReasonsByIds(com.microsoft.bingads.v9.campaignmanagement.GetEditorialReasonsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.AddAdExtensionsResponse addAdExtensions(com.microsoft.bingads.v9.campaignmanagement.AddAdExtensionsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetAdExtensionsByIdsResponse getAdExtensionsByIds(com.microsoft.bingads.v9.campaignmanagement.GetAdExtensionsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.UpdateAdExtensionsResponse updateAdExtensions(com.microsoft.bingads.v9.campaignmanagement.UpdateAdExtensionsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.EditorialApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.DeleteAdExtensionsResponse deleteAdExtensions(com.microsoft.bingads.v9.campaignmanagement.DeleteAdExtensionsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetAdExtensionsEditorialReasonsResponse getAdExtensionsEditorialReasons(com.microsoft.bingads.v9.campaignmanagement.GetAdExtensionsEditorialReasonsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.SetAdExtensionsAssociationsResponse setAdExtensionsAssociations(com.microsoft.bingads.v9.campaignmanagement.SetAdExtensionsAssociationsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.EditorialApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetAdExtensionsAssociationsResponse getAdExtensionsAssociations(com.microsoft.bingads.v9.campaignmanagement.GetAdExtensionsAssociationsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.DeleteAdExtensionsAssociationsResponse deleteAdExtensionsAssociations(com.microsoft.bingads.v9.campaignmanagement.DeleteAdExtensionsAssociationsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetAdExtensionIdsByAccountIdResponse getAdExtensionIdsByAccountId(com.microsoft.bingads.v9.campaignmanagement.GetAdExtensionIdsByAccountIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.AddMediaResponse addMedia(com.microsoft.bingads.v9.campaignmanagement.AddMediaRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetMediaByIdsResponse getMediaByIds(com.microsoft.bingads.v9.campaignmanagement.GetMediaByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetAdGroupCriterionsByIdsResponse getAdGroupCriterionsByIds(com.microsoft.bingads.v9.campaignmanagement.GetAdGroupCriterionsByIdsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetAdGroupCriterionsByAdGroupIdResponse getAdGroupCriterionsByAdGroupId(com.microsoft.bingads.v9.campaignmanagement.GetAdGroupCriterionsByAdGroupIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.AddAdGroupCriterionsResponse addAdGroupCriterions(com.microsoft.bingads.v9.campaignmanagement.AddAdGroupCriterionsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.EditorialApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.UpdateAdGroupCriterionsResponse updateAdGroupCriterions(com.microsoft.bingads.v9.campaignmanagement.UpdateAdGroupCriterionsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.EditorialApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.DeleteAdGroupCriterionsResponse deleteAdGroupCriterions(com.microsoft.bingads.v9.campaignmanagement.DeleteAdGroupCriterionsRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
    public com.microsoft.bingads.v9.campaignmanagement.GetBMCStoresByCustomerIdResponse getBMCStoresByCustomerId(com.microsoft.bingads.v9.campaignmanagement.GetBMCStoresByCustomerIdRequest parameters) throws java.rmi.RemoteException, com.microsoft.bingads.v9.adapi.AdApiFaultDetail, com.microsoft.bingads.v9.campaignmanagement.ApiFaultDetail;
}
